# Makefile
#
TARGET_J  = poisson_j		# Jacobi

SOURCES	= main.c print.c alloc3d.c frobenius.c matrix_init.c matrix_overwrite.c
OBJECTS	= print.o alloc3d.o frobenius.o matrix_init.o matrix_overwrite.o
MAIN_J	= main_j.o
MAIN_GS = main_gs.o
OBJS_J	= $(MAIN_J) jacobi.o

# options and settings for the GCC compilers
#
CC	= suncc
DEFS	= 
OPT	= -g -O3 -fopenmp -xinstrument=datarace
IPO	= 
ISA	= 
CHIP	= 
ARCH	= 
PARA	= 
CFLAGS	= $(DEFS) $(ARCH) $(OPT) $(ISA) $(CHIP) $(IPO) $(PARA) $(XOPTS)
LDFLAGS = -lm 

all: $(TARGET_J)

$(TARGET_J): $(OBJECTS) $(OBJS_J)
	$(CC) -o $@ $(CFLAGS) $(OBJS_J) $(OBJECTS) $(LDFLAGS)

$(MAIN_J):
	$(CC) -o $@ -D_JACOBI $(CFLAGS) -c main.c 


clean:
	@/bin/rm -f core *.o *~

realclean: clean
	@/bin/rm -f $(TARGET_J)  $(TARGET_GS)

# DO NOT DELETE

main_j.o: main.c print.h jacobi.h frobenius.h matrix_init.h matrix_overwrite.h
jacobi.o: jacobi.h
frobenious.o: frobenius.h
matrix_init.o: matrix_init.h
print.o: print.h
matrix_overwrite.o: matrix_overwrite.h
